spring:
  application:
    name: gateway-server
  profiles:
    active: "default"
  config:
    import: "configserver:http://localhost:8090/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

