spring:
  application:
    name: user-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-userms
    username: 1234
    password: emir
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8080
